# Generated by Django 5.1.7 on 2025-12-07 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=50)),
                ('business_description', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('store_category', models.CharField(max_length=50)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('business_document', models.FileField(blank=True, null=True, upload_to='business_docs/')),
                ('authorized', models.BooleanField()),
                ('payment_method', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('digital_wallet_number', models.CharField(blank=True, max_length=50, null=True)),
                ('agreed_terms', models.BooleanField()),
                ('agreed_authenticity_policy', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
