# Generated by Django 5.1.7 on 2025-12-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_selleronboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleronboarding',
            name='agreed_authenticity_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='business_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='store_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleronboarding',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
