# Generated by Django 5.1.7 on 2025-12-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_selleronboarding_agreed_authenticity_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleronboarding',
            name='authorized',
        ),
    ]
