# Generated by Django 5.1.7 on 2025-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customerprofile_phone_customerprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
