# Generated by Django 5.1.7 on 2025-12-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile',
        ),
    ]
