# Generated by Django 5.1.7 on 2025-12-14 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customerprofile_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='role',
            field=models.CharField(default='seller', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
