# Generated by Django 5.1.7 on 2026-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
