# Generated by Django 5.1.7 on 2026-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_seller_verification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selleronboarding',
            options={},
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='selleronboarding',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Admin verification for seller authenticity and documents'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
