# Generated by Django 5.1.7 on 2026-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_selleronboarding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, help_text="User's shipping address", null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.TextField(blank=True, help_text="User's shipping/business address", null=True),
        ),
    ]
