# Generated by Django 5.1.7 on 2026-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_address_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full shipping address', null=True),
        ),
    ]
