# Generated by Django 5.1.7 on 2026-04-07 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customerprofile_green_points_greenpointstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleronboarding',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be up to 10 digits. Optionally start with '+' or '1'.", regex='^\\+?1?\\d{1,10}$')]),
        ),
    ]
