# Generated by Django 5.1.7 on 2026-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount from points', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Green points earned from this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(default=0, help_text='Green points used for discount'),
        ),
    ]
