# Generated by Django 5.1.7 on 2026-01-06 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='product',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Admin verification for product quality and authenticity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
