# Generated by Django 5.1.7 on 2026-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('recycled_items', 'Recycled Items'), ('organic_products', 'Organic Products'), ('energy_efficient', 'Energy-Efficient'), ('reusable_household', 'Reusable Household'), ('handmade_ecocraft', 'Handmade Eco-Crafts'), ('sustainable_fashion', 'Sustainable Fashion'), ('eco_home_garden', 'Eco Home & Garden')], default='recycled_items', help_text='Product category', max_length=50),
        ),
    ]
