# Generated by Django 5.1.7 on 2026-02-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Recycled Items', 'Organic Products')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'FaRecycle', 'FaLeaf')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible to users')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eco Category',
                'verbose_name_plural': 'Eco Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('recycled_items', 'Recycled Items'), ('organic_products', 'Organic Products'), ('energy_efficient', 'Energy-Efficient'), ('reusable_household', 'Reusable Household'), ('handmade_ecocraft', 'Handmade Eco-Crafts'), ('sustainable_fashion', 'Sustainable Fashion'), ('eco_home_garden', 'Eco Home & Garden')], default='recycled_items', help_text='Legacy category (will be migrated to eco_category)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_category',
            field=models.ForeignKey(blank=True, help_text='Dynamic eco category (managed by admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.ecocategory'),
        ),
    ]
