# Generated by Django 5.1.7 on 2026-02-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_eco_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecocategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Eco Category', 'verbose_name_plural': 'Eco Categories'},
        ),
        migrations.RemoveField(
            model_name='ecocategory',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='ecocategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying categories'),
        ),
        migrations.AlterField(
            model_name='ecocategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this category'),
        ),
        migrations.AlterField(
            model_name='ecocategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-leaf')", max_length=50),
        ),
        migrations.AlterField(
            model_name='ecocategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active'),
        ),
        migrations.AlterField(
            model_name='ecocategory',
            name='name',
            field=models.CharField(help_text="Category name (e.g., 'Organic Products')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ecocategory',
            name='slug',
            field=models.SlugField(help_text="URL-friendly version (e.g., 'organic_products')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eco_category',
            field=models.ForeignKey(blank=True, help_text='Dynamic eco category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ecocategory'),
        ),
    ]
