# Generated by Django 5.1.7 on 2026-02-01 18:30

from django.db import migrations

def populate_eco_categories(apps, schema_editor):
    """Populate EcoCategory table with default categories"""
    EcoCategory = apps.get_model('products', 'EcoCategory')
    
    categories = [
        {
            'name': 'Recycled Items',
            'slug': 'recycled_items',
            'description': 'Products made from recycled materials, giving new life to waste.',
            'icon': 'fa-recycle',
            'display_order': 1
        },
        {
            'name': 'Organic Products',
            'slug': 'organic_products',
            'description': 'Certified organic products free from harmful chemicals.',
            'icon': 'fa-leaf',
            'display_order': 2
        },
        {
            'name': 'Energy-Efficient',
            'slug': 'energy_efficient',
            'description': 'Products designed to reduce energy consumption.',
            'icon': 'fa-bolt',
            'display_order': 3
        },
        {
            'name': 'Reusable Household',
            'slug': 'reusable_household',
            'description': 'Durable household items that replace single-use products.',
            'icon': 'fa-home',
            'display_order': 4
        },
        {
            'name': 'Handmade Eco-Crafts',
            'slug': 'handmade_ecocraft',
            'description': 'Artisan-made products using sustainable materials.',
            'icon': 'fa-hand-paper',
            'display_order': 5
        },
        {
            'name': 'Sustainable Fashion',
            'slug': 'sustainable_fashion',
            'description': 'Ethically made clothing and accessories.',
            'icon': 'fa-tshirt',
            'display_order': 6
        },
        {
            'name': 'Eco Home & Garden',
            'slug': 'eco_home_garden',
            'description': 'Eco-friendly products for home and garden care.',
            'icon': 'fa-seedling',
            'display_order': 7
        }
    ]
    
    for category_data in categories:
        EcoCategory.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )

def reverse_populate_eco_categories(apps, schema_editor):
    """Remove the populated categories"""
    EcoCategory = apps.get_model('products', 'EcoCategory')
    EcoCategory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_eco_category'),
    ]

    operations = [
        migrations.RunPython(populate_eco_categories, reverse_populate_eco_categories),
    ]
