# Generated by Django 5.1.7 on 2026-02-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_populate_eco_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Accessories')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly version (e.g., 'accessories')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-heart')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Product category (Accessories, Kitchen Items, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory'),
        ),
    ]
